# Generated by Django 5.2 on 2025-04-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0003_customchart_delete_customplotlychart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customchart",
            name="js_code",
        ),
        migrations.AddField(
            model_name="customchart",
            name="config_json",
            field=models.TextField(
                default="{}", help_text="Raw Chart.js config as JSON string."
            ),
            preserve_default=False,
        ),
    ]
