# Generated by Django 5.2 on 2025-04-10 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0004_remove_customchart_js_code_customchart_config_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customchart",
            name="config_json",
        ),
        migrations.RemoveField(
            model_name="customchart",
            name="created_at",
        ),
        migrations.AddField(
            model_name="customchart",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("bar", "Bar"),
                    ("line", "Line"),
                    ("pie", "Pie"),
                    ("doughnut", "Doughnut"),
                ],
                default="bar",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customchart",
            name="data",
            field=models.JSONField(
                default=[], help_text="List of values for each label"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customchart",
            name="labels",
            field=models.JSONField(
                default=[], help_text="List of x-axis labels (e.g., days of week)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customchart",
            name="options",
            field=models.JSONField(
                blank=True, help_text="Optional Chart.js config options", null=True
            ),
        ),
        migrations.AlterField(
            model_name="customchart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
