# Generated by Django 5.2 on 2025-04-10 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0005_remove_customchart_config_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customchart",
            name="data",
        ),
        migrations.RemoveField(
            model_name="customchart",
            name="labels",
        ),
        migrations.RemoveField(
            model_name="customchart",
            name="options",
        ),
        migrations.AddField(
            model_name="customchart",
            name="config_code",
            field=models.TextField(
                default="{}",
                help_text="Python code that sets `chart_config` as a Chart.js config dict.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customchart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customchart",
            name="chart_type",
            field=models.CharField(default="bar", max_length=50),
        ),
    ]
