# Generated by Django 5.2 on 2025-04-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_logic",
            "0006_remove_customchart_data_remove_customchart_labels_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customchart",
            name="card_size",
            field=models.CharField(
                choices=[
                    ("sm", "Small"),
                    ("md", "Medium"),
                    ("lg", "Large"),
                    ("xl", "Extra Large"),
                    ("full", "Full Width"),
                ],
                default="md",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customchart",
            name="pages",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="customchart",
            name="render_code",
            field=models.TextField(
                default="{}", help_text="Python code that returns Chart.js config."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customchart",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
