# Generated by Django 5.2 on 2025-04-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0007_customchart_card_size_customchart_pages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customchart",
            name="render_code",
        ),
    ]
