# Generated by Django 5.2 on 2025-04-10 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0008_remove_customchart_render_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMetricCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("KIT_SUCCESS", "KIT_SUCCESS"),
                            ("KIT_ERROR", "KIT_ERROR"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("today", "Today"),
                            ("month", "Last 30 Days"),
                            ("year", "Last 365 Days"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, help_text="Optional emoji or icon", max_length=5
                    ),
                ),
                ("color_class", models.CharField(default="bg-gray-50", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
