# Generated by Django 5.2 on 2025-04-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0011_detectionlabel_modelperformanceimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="event_code",
            field=models.CharField(default={}, max_length=255),
            preserve_default=False,
        ),
    ]
