# Generated by Django 5.2 on 2025-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0012_eventdefinition_event_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdefinition",
            name="event_code",
        ),
        migrations.AddField(
            model_name="eventdefinition",
            name="event_definition_code",
            field=models.TextField(blank=True),
        ),
    ]
