# Generated by Django 5.2 on 2025-04-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0013_remove_eventdefinition_event_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdefinition",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
