# Generated by Django 5.2 on 2025-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0014_eventdefinition_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionlabel",
            name="image",
        ),
        migrations.AddField(
            model_name="detectionlabel",
            name="image_with_box",
            field=models.ImageField(blank=True, null=True, upload_to="label_examples/"),
        ),
    ]
