# Generated by Django 5.2 on 2025-04-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_logic", "0015_remove_detectionlabel_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsrecipient",
            name="message_template",
            field=models.TextField(
                blank=True,
                help_text="Custom message format. You can use these placeholders: {event_type}, {timestamp}, {camera}, {user}, {gif_url}",
            ),
        ),
    ]
