# Generated by Django 5.2 on 2025-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
