# Generated by Django 5.2 on 2025-04-05 20:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_event_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="media/event_thumbnails"
                ),
                upload_to="event_thumbnails/",
            ),
        ),
    ]
