# Generated by Django 5.2 on 2025-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0007_event_gif"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="people",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
