# Generated by Django 5.2 on 2025-04-07 19:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0008_event_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="event",
            name="gif_thumb",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="media/event_thumbnails"
                ),
                upload_to="event_gifs/thumbs/",
            ),
        ),
    ]
